Changes for deployment events:
craftercms/deployer pull request #123
Opened 2019-03-17 18:17 UTC by avasquez614

* Added processor that saves cache clear/rebuild context events in a file.
* Added originalChangeSet to list of parameters of AbstractMainDeploymentProcessor.doExecute so processors can modify the change set of the deployment.

Ticket craftercms/craftercms#2935

2019-03-18 15:25 UTC, sumerjabri requested changes

2019-03-18 15:25 UTC, sumerjabri commented on src/main/java/org/craftercms/deployer/impl/processors/FileBasedDeploymentEventProcessor.java
> +package org.craftercms.deployer.impl.processors;
Missing copyright notice.

2019-03-18 15:25 UTC, sumerjabri commented on src/main/java/org/craftercms/deployer/impl/processors/FileBasedDeploymentEventProcessor.java
> +    private static final Logger logger = LoggerFactory.getLogger(FileBasedDeploymentEventProcessor.class);
Line too long.

2019-03-19 03:30 UTC, avasquez614 commented on src/main/java/org/craftercms/deployer/impl/processors/FileBasedDeploymentEventProcessor.java
> +    private static final Logger logger = LoggerFactory.getLogger(FileBasedDeploymentEventProcessor.class);
Discussed this, won't change the size, we'll look later on a way to expand the GitHub editor.

2019-03-19 18:41 UTC, sumerjabri requested changes
Missing copyright notice.

2019-03-19 18:46 UTC, avasquez614 commented
Not sure whyt it's not appearing, but the copyright notice is now in the file: https://github.com/craftercms/deployer/blob/f12f2695ba6c580afd2867b46f19764550c0b2b8/src/main/java/org/craftercms/deployer/impl/processors/FileBasedDeploymentEventProcessor.java

2019-03-19 19:17 UTC, sumerjabri approved these changes

2019-03-19 19:17 UTC, merged