Add support for multiple Elasticsearch clusters
craftercms/deployer pull request #188
Opened 2020-01-16 22:46 UTC by jdrossl

https://github.com/craftercms/craftercms/issues/3761

Depends on https://github.com/craftercms/search/pull/193

2020-01-17 20:26 UTC, avasquez614 requested changes
I think we are missing `readCluster` and `writeClusters` sections in the `base-config.yaml` of the craftercms bundle, just commented out. So that people know these properties exist.

2020-01-17 20:26 UTC, avasquez614 commented on src/main/resources/base-target-context.xml
> +        <constructor-arg value="${${target.search.elasticsearch.settings.preview}}"/>
why double `${`?

2020-01-17 20:43 UTC, jdrossl commented
> I think we are missing `readCluster` and `writeClusters` sections in the `base-config.yaml` of the craftercms bundle, just commented out. So that people know these properties exist.

I'll update it

2020-01-20 15:18 UTC, avasquez614 approved these changes

2020-01-20 15:34 UTC, merged