Refactor for scripting:
craftercms/deployer pull request #289
Opened 2021-01-22 22:26 UTC by jdrossl

- Move classes to commons

craftercms/craftercms#4390

Depends on https://github.com/craftercms/commons/pull/260

2021-01-27 15:23 UTC, avasquez614 requested changes

2021-01-27 15:23 UTC, avasquez614 commented on src/main/java/org/craftercms/deployer/impl/upgrade/operations/AddProcessorUpgradeOperation.java
> + * @author joseross
Missing class description?

2021-01-27 15:23 UTC, avasquez614 commented on src/main/java/org/craftercms/deployer/impl/upgrade/operations/ConditionalEnvUpgradeOperation.java
> + *
Missing class description?

2021-02-01 21:24 UTC, sumerjabri approved these changes

2021-02-01 21:24 UTC, merged