Improvement for script sandbox:
craftercms/deployer pull request #306
Opened 2021-05-26 22:31 UTC by jdrossl

- Add new restrictions for Groovy

craftersoftware/craftercms#240

Depends on craftercms/script-security-plugin#13

2021-05-27 19:56 UTC, avasquez614 approved these changes

2021-05-27 20:03 UTC, avasquez614 requested changes

2021-05-27 20:03 UTC, avasquez614 commented on src/main/resources/application.yaml
> +        blacklist:
Please add doc indicating these variables only works if sandbox is enabled

2021-05-28 13:48 UTC, sumerjabri commented on src/main/resources/application.yaml
> +          # (this will have no effect if the sandbox is disabled)
Please clarify `sandbox`. Either name it clearly or link a doc. Ping me to discuss options.

2021-05-28 14:18 UTC, sumerjabri approved these changes

2021-05-28 14:26 UTC, sumerjabri approved these changes

2021-05-28 14:27 UTC, merged