Refactor to add new Elasticsearch API Client
craftercms/deployer pull request #341
Opened 2022-01-24 22:59 UTC by jdrossl

https://github.com/craftercms/craftercms/issues/5210

Depends on https://github.com/craftercms/search/pull/267

2022-01-27 15:52 UTC, sumerjabri requested changes

2022-01-27 15:52 UTC, sumerjabri commented on src/main/java/org/craftercms/deployer/utils/elasticsearch/AbstractElasticsearchFactory.java
> +//        logger.debug("Closing all clients for '{}'", name);
Why keep these around?

2022-01-27 15:52 UTC, sumerjabri commented on src/main/java/org/craftercms/deployer/utils/elasticsearch/legacy/AbstractElasticsearchFactory.java
> + * Copyright (C) 2007-2020 Crafter Software Corporation. All Rights Reserved.
Please update to 2022

2022-01-27 15:52 UTC, sumerjabri commented on src/main/java/org/craftercms/deployer/utils/elasticsearch/legacy/ElasticsearchClusterConfig.java
> + * Copyright (C) 2007-2020 Crafter Software Corporation. All Rights Reserved.
2022

2022-01-27 15:52 UTC, sumerjabri commented on src/main/java/org/craftercms/deployer/utils/elasticsearch/legacy/ElasticsearchConfig.java
> + * Copyright (C) 2007-2020 Crafter Software Corporation. All Rights Reserved.
2022

2022-01-27 15:53 UTC, avasquez614 approved these changes

2022-01-31 19:53 UTC, sumerjabri approved these changes

2022-01-31 19:54 UTC, merged