[3.1] Add auto-repair for locked/corrupted git repos
craftercms/deployer pull request #355
Opened 2022-05-20 11:06 UTC by phuongnq

### Ticket reference or full description of what's in the PR
https://github.com/craftercms/craftercms/issues/5600

2022-05-20 14:26 UTC, sumerjabri requested changes
I think we need to clean things up on startup only, not on every pull. @jdrossl correct me if I'm wrong here.

2022-05-20 14:26 UTC, sumerjabri commented on src/main/java/org/craftercms/deployer/impl/processors/git/GitPullProcessor.java
> +                    logger.info(".git/index.lock is deleted from local repository {}", localRepoFolder);
Please use '{}' as a standard placeholder (I'm trying to have the whole system be consistent).

2022-05-20 15:15 UTC, jdrossl commented
I'm ok with checking on every pull, it integrates with how the system recovers from the corrupted index

2022-05-20 15:16 UTC, jdrossl approved these changes

2022-05-20 16:27 UTC, sumerjabri commented
> I'm ok with checking on every pull, it integrates with how the system recovers from the corrupted index

What about an externally held lock?

@avasquez614 @russdanner how realistic is it to have an externally held lock? Should we do this on startup only or on every pull? (this is Deployer)

2022-05-23 15:44 UTC, sumerjabri requested changes
Please make it clean up on start up only.

2022-05-24 08:08 UTC, phuongnq commented
Modified so that on startup, check for targets that need unlock.

2022-05-24 14:40 UTC, jdrossl approved these changes

2022-05-24 18:58 UTC, sumerjabri approved these changes

2022-05-24 18:58 UTC, merged