Index xml as binary to bind contentLength field
craftercms/deployer pull request #371
Opened 2022-10-07 05:04 UTC by phuongnq

### Ticket reference or full description of what's in the PR
https://github.com/craftercms/craftercms/issues/5812

2022-10-07 15:52 UTC, avasquez614 requested changes
@phuongnq why are we indexing XML as binaries? That makes no sense to me

2022-10-07 15:56 UTC, sumerjabri commented
@phuongnq This issue was the result of this https://github.com/craftercms/deployer/commit/b6b04b0c4b29b0501a95af3447922f517b49b8ea which was intended to fix this issue: https://github.com/craftercms/craftercms/issues/5793

I don't clearly understand how jackets are associated with binaries. Let's understand better what the `binaryPathPatterns` is actually being used for and how jacket meta-data is being propagated to binaries.

2022-10-10 04:20 UTC, phuongnq commented
@sumerjabri @avasquez614 You are right. It is not correct to index XML as binary. We only want to have `contentLength` and content-type related metadata (such as `thumbnail`) which was missing after we did https://github.com/craftercms/deployer/commit/b6b04b0c4b29b0501a95af3447922f517b49b8ea update.
I have created a new `metadataExtractorPathPatterns` to address this as `metadataPathPatterns` is mainly used for the jacket. (I do think that `metadaPathPatterns` was overused for both the jacket and the extractors previously)
Assuming the extra metadata extractors (`contentTypeMetadataExtractor`, `fileSizeMetadataExtractor`) are only for authoring, I only put this to the authoring target.

2022-10-10 14:26 UTC, sumerjabri approved these changes

2022-10-10 14:26 UTC, merged