Update S3 DeleteObjectsRequest to take up to 1000 keys
craftercms/deployer pull request #387
Opened 2023-05-23 08:28 UTC by phuongnq

### Ticket reference or full description of what's in the PR
https://github.com/craftersoftware/craftercms/issues/542

2023-05-23 15:40 UTC, jmendeza requested changes

2023-05-23 15:40 UTC, jmendeza commented on src/main/java/org/craftercms/deployer/impl/processors/aws/S3SyncProcessor.java
> +                while (start < keys.size()) {
May I suggest try using something like `org.apache.commons.collections4.ListUtils.partition` instead of manually partition the list

```
for (List<String> subList : ListUtils.partition(keys, MAX_DELETE_KEYS_PER_REQUEST)) {
    // Create and execute delete request
}
```

2023-05-24 01:13 UTC, phuongnq commented on src/main/java/org/craftercms/deployer/impl/processors/aws/S3SyncProcessor.java
> +                while (start < keys.size()) {
Updated. Thank you!

2023-05-24 15:01 UTC, jmendeza approved these changes

2023-05-24 17:04 UTC, sumerjabri approved these changes

2023-05-24 17:04 UTC, merged